'use strict';

const ASK_DONE = 'ASK_DONE';
const NO_QUESTION_FOUND = 'no question found';
const QUESTION_LIST_NOT_FOUND = 'question list not found';
const ASK_INIT = 'ASK_INIT';

const DONE = 'DONE';
const ERROR = 'ERROR';

const BROWSER_STEALTH_CHECK_OK = 'BROWSER_STEALTH_CHECK_OK';
const BROWSER_STEALTH_CHECK_FAIL = 'BROWSER_STEALTH_CHECK_FAIL';
const BROWSER_STEALTH_CHECK_INIT = 'BROWSER_STEALTH_CHECK_INIT';

module.exports = {
  ASK_DONE,
  NO_QUESTION_FOUND,
  QUESTION_LIST_NOT_FOUND,
  ASK_INIT,
  BROWSER_STEALTH_CHECK_OK,
  BROWSER_STEALTH_CHECK_FAIL,
  BROWSER_STEALTH_CHECK_INIT,
  DONE,
  ERROR,
};
