services:
  coze_proxy:
    build: .
    image: bincooo/chatgpt-adapter:latest
    restart: always
    command: sleep infinity
    ports:
      - '8080:8080'
    volumes:
      - ./config.yaml:/app/config.yaml
