services:
  mongo:
    image: mongo:latest
    # container_name: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/data/db:/data/db
      - ./volumes/mongo/data/configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    # container_name: mongo-express
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8081:8081
    depends_on:
      - mongo

  dbapi:
    build: ./dbapi
    ports:
      - 3001:3001
    volumes:
      - ./dbapi:/app
    depends_on:
      - mongo
