services:
  openbox-poe-seat1:
    # image: logickee/openbox-poe-seat
    image: logickee/openbox-seat-tester-final
    shm_size: "2gb"
    ports:
      - 6081:6080
      - 3021:3000
      - 5901:5900
    privileged: true
    volumes:
      # NOTE: share firfox user profile
      - ./volumes/openbox-poe-seat1/firefox-user-data:/workspace/firefox-user-data

      # NOTE: share chrome user profile
      - ./volumes/openbox-poe-seat1/chrome-user-data:/workspace/chrome-user-data
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share

      # NOTE: source code
      - "./src:/app"
    environment:
      - TZ=Asia/Hong_Kong
      - FIREFOX_DATA_DIR=/workspace/firefox-user-data
      - CHROME_DATA_DIR=/workspace/chrome-user-data
    # command: sleep infinity
