services:
  # openbox-firefox:
  #   image: openbox-poe-seat
  #   ports:
  #     - 6080:6080
  #     - 3000:3000
  #     - 5900:5900
  #   privileged: true
  #   volumes:
  #     - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
  #     # - ./src/openbox-firefox/share/firefox-user-data:/share/firefox-user-data

  #     # NOTE: share firfox user profile
  #     - ./volumes/openbox-firefox/firefox-user-data:/share/firefox-user-data

  #     # NOTE: share chrome user profile
  #     - ./volumes/openbox-firefox/chrome-user-data:/share/chrome-user-data
      
  #     # NOTE: store output
  #     - ./volumes/static-share/_output:/share

  #     # NOTE: source code
  #     - "./openbox-poe-seat/src:/app"
  #   environment:
  #     - TZ=Asia/Hong_Kong
  #   # command: sleep infinity

  openbox-poe-seat1:
<<<<<<<< HEAD:poe-tryout/docker-poe-tryout/src/openbox-poe-seat/docker-compose.yml
    image: logickee/openbox-poe-seat
========
    image: logickee/openbox-seat-ubuntu
>>>>>>>> ef57d69 (update,):poe-tryout/docker-poe-tryout/src/openbox-seat/docker-compose.yml
    ports:
      - 6081:6080
      - 3021:3000
      - 5901:5900
    privileged: true
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      # - ./src/openbox-firefox/share/firefox-user-data:/share/firefox-user-data

      # NOTE: share firfox user profile
      - ./volumes/openbox-poe-seat1/firefox-user-data:/share/firefox-user-data

      # NOTE: share chrome user profile
      - ./volumes/openbox-poe-seat1/chrome-user-data:/share/chrome-user-data
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share

      # NOTE: source code
      - "./openbox-poe-seat/src:/app"
    environment:
      - TZ=Asia/Hong_Kong
    # command: sleep infinity

  openbox-poe-seat2:
<<<<<<<< HEAD:poe-tryout/docker-poe-tryout/src/openbox-poe-seat/docker-compose.yml
    image: logickee/openbox-poe-seat
========
    image: logickee/openbox-seat-ubuntu
>>>>>>>> ef57d69 (update,):poe-tryout/docker-poe-tryout/src/openbox-seat/docker-compose.yml
    ports:
      - 6082:6080
      - 3022:3000
      - 5902:5900
    privileged: true
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      # - ./src/openbox-firefox/share/firefox-user-data:/share/firefox-user-data

      # NOTE: share firfox user profile
      - ./volumes/openbox-poe-seat2/firefox-user-data:/share/firefox-user-data

      # NOTE: share chrome user profile
      - ./volumes/openbox-poe-seat2/chrome-user-data:/share/chrome-user-data
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share

      # NOTE: source code
      - "./openbox-poe-seat/src:/app"
    environment:
      - TZ=Asia/Hong_Kong
    # command: sleep infinity
    
  # openbox-seat3:
  #   image: logickee/openbox-poe-seat
  #   ports:
  #     - 6083:6080
  #     - 3023:3000
  #     - 5903:5900
  #   privileged: true
  #   volumes:
  #     - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
  #     # - ./src/openbox-firefox/share/firefox-user-data:/share/firefox-user-data

  #     # NOTE: share firfox user profile
  #     - ./volumes/openbox-seat3/firefox-user-data:/share/firefox-user-data

  #     # NOTE: share chrome user profile
  #     - ./volumes/openbox-seat3/chrome-user-data:/share/chrome-user-data
      
  #     # NOTE: store output
  #     - ./volumes/static-share/_output:/share

  #     # NOTE: source code
  #     - "./openbox-poe-seat/src:/app"
  #   environment:
  #     - TZ=Asia/Hong_Kong
  #   # command: sleep infinity
