services:
  flow-handler:
    # build: ./flow-handler
    image: logickee/poe-tryout-flow-handler
    entrypoint: ./entry.sh
    # command: sleep infinity
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./flow-handler/src:/app
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share
      - ./volumes/logs:/logs
      
      # - ./volumes/flow-handler/screenshot:/share/screenshot
    working_dir: /app

    # TODO:
    # depends_on:
    #   - mongo
    depends_on:
      poe-scheduler-api:
        condition: service_started
      link-extractor-chrome:
        condition: service_started
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong