services:
  flow-handler:
    # build: ./flow-handler
    image: logickee/poe-tryout-flow-handler
    command: ./entry.sh
    # command: sleep infinity
    volumes:
      - ./flow-handler/src:/app
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share

      # - ./volumes/flow-handler/screenshot:/share/screenshot
    working_dir: /app
    depends_on:
      poe-scheduler-api:
        condition: service_started
      link-extractor-chrome:
        condition: service_started
    ports:
      - 3005:3000
