services:
  flow-handler:
    # build: ./flow-handler
    image: 192.168.10.61:5000/poe-tryout-flow-handler
    # image: logickee/poe-tryout-flow-handler
    entrypoint: ./entry.sh
    # command: sleep infinity
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./flow-handler/src:/app
      
      # NOTE: store output
      - ./volumes/static-share/_output:/share
      - ./volumes/logs:/logs
      
      # - ./volumes/flow-handler/screenshot:/share/screenshot
    working_dir: /app

    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
    env_file: ./.env

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 5

    depends_on:
      poe-scheduler-api:
        condition: service_healthy
      jobsdb-link-extractor:
        condition: service_healthy
      page-handler:
        condition: service_healthy

    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"
