services:
  bait:
    # build: ./bait
    image: 192.168.10.61:5000/poe-tryout-bait 
    volumes:
      - "./bait/src:/app"
    working_dir: /app
    ports:
      - 18089:8080
    command: ./entry.sh
    restart: unless-stopped
