// states

const HELLOWORLD_STATE = 'HELLOWORLD_STATE';

const STATE_INIT = 'STATE_INIT';
const STATE_START = 'STATE_START';
const STATE_SCHEDULED = 'STATE_SCHEDULED';
const STATE_DONE = 'STATE_DONE';

module.exports = {
  //
  HELLOWORLD_STATE,
  STATE_INIT,
  STATE_START,
  STATE_SCHEDULED,
  STATE_DONE,
};
