FROM openbox-firefox-ubuntu

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

RUN apt --fix-broken install -y ./google-chrome-stable_current_amd64.deb

RUN rm -rf google-chrome-stable_current_amd64.deb
