networks:
  default:
    name: poe-tryout

services:
  test:
    image: node:latest
    command: sleep infinity
    working_dir: /src
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./:/src
      - /run/docker.sock:/run/docker.sock:ro
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ=Asia/Hong_Kong
  #   build: ./docker-ubuntu2
  # ubuntu3:
  #   build: ./docker-ubuntu3
