networks:
  default:
    name: poe-tryout

services:
  test:
    cpus: 0.05
    image: node:latest
    command: sleep infinity
    working_dir: /src
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./:/src
      - /run/docker.sock:/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - REDIS_ENDPOINT_URI=redis://diff-handler-redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file: ./.env

  busybox: 
    image: busybox 
    command: sleep infinity

  #   build: ./docker-ubuntu2
  # ubuntu3:
  #   build: ./docker-ubuntu3
