name: jobsdb-poe

networks:
  default:
    name: jobsdb-poe-network

services:
  test:
    image: node:latest
    command: sleep infinity
    working_dir: /src
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./:/src
      - /run/docker.sock:/run/docker.sock:ro
      - ./volumes/static-share/_output:/share

    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - REDIS_ENDPOINT_URI=redis://diff-handler-redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file: ./.env

    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"

  busybox: 
    image: busybox 
    command: sleep infinity

    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"

  #   build: ./docker-ubuntu2
  # ubuntu3:
  #   build: ./docker-ubuntu3
