networks:
  default:
    name: poe-tryout

services:
  debug:
    image: node:latest
    command: sleep infinity
    working_dir: /src
    volumes:
      - ./:/src
  #   build: ./docker-ubuntu2
  # ubuntu3:
  #   build: ./docker-ubuntu3
