networks:
  default:
    name: poe-tryout

services:
  test:
    image: node:latest
    command: sleep infinity
    working_dir: /src
    env_file: ./.env
    volumes:
      - ./:/src
    restart: unless-stopped
  #   build: ./docker-ubuntu2
  # ubuntu3:
  #   build: ./docker-ubuntu3
