services:
  jobsdb-link-extractor:
    # build: ./jobsdb-link-extractor
    image: logickee/poe-tryout-jobsdb-link-extractor
    command: ./entry.sh
    # command: sleep infinity
    volumes:
      - ./jobsdb-link-extractor/src:/app
      - ./volumes/jobsdb-link-extractor/screenshot:/share/screenshot
      - ./volumes/jobsdb-link-extractor:/share
    working_dir: /app
    depends_on:
      link-extractor-chrome:
        condition: service_started
    ports:
      - 3003:3000
    restart: unless-stopped
    
  link-extractor-chrome:
    image: browserless/chrome
    shm_size: "1gb"
    restart: unless-stopped
    ports:
      - 13000:3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
