services:
  jobsdb-link-extractor:
    build: ./jobsdb-link-extractor
    # image: ubuntu:latest
    command: sleep infinity
    volumes:
      - ./jobsdb-link-extractor/src:/app
      - ./volumes/jobsdb-link-extractor/screenshot:/share/screenshot
    working_dir: /app
    depends_on:
      link-extractor-chrome:
        condition: service_started

  link-extractor-chrome:
    image: browserless/chrome
    restart: unless-stopped
    ports:
      - 13000:3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
