services:
  jobsdb-link-extractor:
    # build: ./jobsdb-link-extractor
    image: 192.168.10.61:5000/poe-tryout-jobsdb-link-extractor
    # image: logickee/poe-tryout-jobsdb-link-extractor
    entrypoint: ./entry.sh
    # command: sleep infinity
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - /run/docker.sock:/run/docker.sock:ro
      - ./jobsdb-link-extractor/src:/app
      - ./volumes/jobsdb-link-extractor/screenshot:/share/screenshot
      - ./volumes/jobsdb-link-extractor:/share
      - ./volumes/logs:/logs
    working_dir: /app
    ports:
      - 3003:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - LOG_PREFIX=jobsdb-link-extractor
      - PLAYWRIGHT_DRIVER_URL=ws://browserless-chrome:3000/?stealth=1&--disable-web-security=true
    env_file: ./.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      - browserless-chrome

    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"

  # link-extractor-chrome:
  #   image: browserless/chrome
  #   shm_size: '1gb'
  #   restart: unless-stopped
  #   ports:
  #     - 13000:3000
  #   environment:
  #     - TZ=Asia/Hong_Kong
  #     - SCREEN_WIDTH=1920
  #     - SCREEN_HEIGHT=1024
  #     - SCREEN_DEPTH=16
  #     - ENABLE_DEBUGGER=false
  #     - PREBOOT_CHROME=true
  #     - CONNECTION_TIMEOUT=300000
  #     - MAX_CONCURRENT_SESSIONS=10
  #     - CHROME_REFRESH_TIME=600000
  #     - DEFAULT_BLOCK_ADS=true
  #     - DEFAULT_STEALTH=true
  #     - DEFAULT_IGNORE_HTTPS_ERRORS=true
  #   volumes:
  #     - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
