volumes:
  redis_data:
  
services:
  poe-scheduler-api:
    # build: ./poe-scheduler-api
    image: 192.168.10.61:5000/poe-tryout-poe-scheduler-api
    # image: logickee/poe-tryout-poe-scheduler-api
    ports:
      - 3002:3002
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./poe-scheduler-api/:/app
      - ./volumes/static-share:/share
      - ./volumes/logs:/logs
    env_file: ./.env

    working_dir: /app
    restart: unless-stopped
    entrypoint: ./entry.sh
    environment:
      - TZ=Asia/Hong_Kong
      - LOG_PREFIX=poe-scheduler-api

    depends_on:
      redis:
        condition: service_healthy      
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"

  redis:
    image: 192.168.10.61:5000/redis:6.0.20
    hostname: redis
    # expose:
    #   - 6379
    ports:
      - 16379:6379
    volumes: 
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - redis_data:/data
    command: redis-server --save 5 1 --loglevel warning --dir /data
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      
    deploy:
      resources:
        limits:
          cpus: "0.7"
        reservations:
          cpus: "0.01"
