services:
  poe-scheduler-api:
    # build: ./poe-scheduler-api
    image: logickee/poe-tryout-poe-scheduler-api
    ports:
      - 3002:3002
    volumes:
      - /usr/share/zoneinfo/Asia/Hong_Kong:/etc/localtime:ro
      - ./poe-scheduler-api/:/app
      - ./volumes/static-share:/share
      - ./volumes/logs:/logs

    # TODO:
    # depends_on:
    #   - mongo
    depends_on:
      - redis
    working_dir: /app
    restart: unless-stopped
    entrypoint: ./dev.sh
    env_file: ./.env
    environment:
      - TZ=Asia/Hong_Kong
      - LOG_PREFIX=poe-scheduler-api
