volumes:
  redisinsight_store:
  redis_data:
  redis_etc_redis:
  
services:
  redis:
    # image: redis:6.0.7
    build: ./redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/etc/redis/redis.conf:/etc/redis/redis.conf
      # - redis_etc_redis:/etc/redis
      # NOTE: related to redis.conf
      - ./volumes/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    # command: sleep infinity
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight_store:/db
    restart: unless-stopped

  poe-scheduler-api:
    # build: ./poe-scheduler-api
    image: logickee/poe-tryout-poe-scheduler-api
    ports:
      - 3002:3002
    volumes:
      - ./poe-scheduler-api/:/app
      - ./volumes/static-share:/share
    depends_on:
      - redis
    restart: unless-stopped
    # command: sleep infinity
