volumes:
  redisinsight_store:
  redis_data:
    driver: local
  redis_etc_redis:
  
services:
  # redis:
  #   image: redis:6.0.7
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./volumes/redis/redis.conf:/redis.conf
  #     - redis_etc_redis:/etc/redis
  #     # NOTE: related to redis.conf
  #     - redis_data:/data
  #   command: redis-server /redis.conf
  #   restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --dir /data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight_store:/db
    depends_on:
      - redis
    restart: unless-stopped

  poe-scheduler-api:
    # build: ./poe-scheduler-api
    image: logickee/poe-tryout-poe-scheduler-api
    ports:
      - 3002:3002
    volumes:
      - ./poe-scheduler-api/:/app
      - ./volumes/static-share:/share
    depends_on:
      - redis
    restart: unless-stopped
    # command: sleep infinity
