services:
  api-debug:
    build: ./api-debug
    # image: ubuntu:latest
    command: ./dev.sh
    # command: sleep infinity
    volumes:
      - ./api-debug/src:/app
      - ./volumes/api-debug:/share
      - ./volumes/logs:/logs
    working_dir: /app
    ports:
      - 3051:3000
    depends_on:
      - redis
      - mongo
