volumes:
  changedetection_data:

services:
  # NOTE: phrase out
  diff-handler:
    # build: ./changedetect/diff-handler
    image: logickee/poe-tryout-diff-handler
    volumes:
      - ./changedetect/diff-handler/src:/app
      - ./volumes/changedetect/diff-handler:/share
    working_dir: /app
    ports:
      - 3052:3000
    command: ./entry.sh
    # command: sleep infinity
    restart: unless-stopped

  jobsdb-scraper:
    # build: ./changedetect/jobsdb-scraper
    image: logickee/poe-tryout-jobsdb-scraper
    volumes:
      - ./changedetect/jobsdb/scraper/src:/app
      - ./volumes/changedetect/jobsdb-scraper:/share
    working_dir: /app
    ports:
      - 3054:3000
    command: ./entry.sh
    # command: sleep infinity
    restart: unless-stopped

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    # container_name: changedetection
    # hostname: changedetection
    volumes:
      - ./volumes/changedetection/datastore:/datastore
      # Configurable proxy list support, see https://github.com/dgtlmoon/changedetection.io/wiki/Proxy-configuration#proxy-list-support
      # - ./proxies.json:/datastore/proxies.json

    environment:
      # Default listening port, can also be changed with the -p option
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://changedetection-chrome:3000/?stealth=1&--disable-web-security=true
      # An exclude list (useful for notification URLs above) can be specified by with
      - NO_PROXY="localhost,192.168.10.0/24"
      # Hides the `Referer` header so that monitored websites can't see the changedetection.io hostname.
      - HIDE_REFERER=true

    # Comment out ports: when using behind a reverse proxy , enable networks: etc.
    ports:
      - 5000:5000
    restart: unless-stopped

    # If WEBDRIVER or PLAYWRIGHT are enabled, changedetection container depends on that
    # and must wait before starting (substitute "browser-chrome" with "changedetection-chrome" if last one is used)
    depends_on:
      changedetection-chrome:
        condition: service_started

  changedetection-chrome:
    #  hostname: changedetection-chrome
    image: browserless/chrome
    shm_size: '1gb'
    restart: unless-stopped
    ports:
      - 3053:3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      # Ignore HTTPS errors, like for self-signed certs
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
