services:
  page-handler:
    # build: ./page-handler
    image: logickee/poe-tryout-page-handler
    entrypoint: ./entry.sh
    # command: sleep infinity
    volumes:
      - ./page-handler/src:/app
      - ./volumes/page-handler:/share
      - ./volumes/logs:/logs
    working_dir: /app
    ports:
      - 3061:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - LOG_PREFIX=page-handler
    env_file: ./.env
